### ISSUE TITLE
Can't initialize

### ISSUE THREAD

**Issue by tristan-mcinnis** [dimays/chunkgpt#11]
First off: really appreciate you putting this together. It is quite a big problem that many people are facing.

So i've cloned the github repo, installed the requirements.txt and within an activated new environment variable. Everything good so far.

In the src/chunkgpt folder i've created a new file called OPENAI_API_KEY.env and simply put my key in there: OPENAI_API_KEY=sk.... (my key). I've also changed one of the examples to myfile.txt just to have a try.

Now when i cd into this src/chunkgpt and try to run chunkgpt.py -- nothing happens? It just puts another line down in terminal. Am I missing any steps? I didn't touch or change the chunkgpt.py file at all.

**Comment by dimays** [comment]
Hi @nexuslux , thanks for checking out ChunkGPT!

It looks like you're trying to run `chunkgpt.py` as an executable, which is not how it's intended to be used.

I'll refer you to the [Installation](https://github.com/dimays/chunkgpt/#installation) and [Usage](https://github.com/dimays/chunkgpt/#usage) sections of the documentation.

Here's some high-level information to get you started on the right path:

## Installation

No need to clone this repo, you can just [install it with pip](https://pip.pypa.io/en/stable/installation/) and use it as a package in your own scripts!

## Usage

You'll need to [import](https://www.digitalocean.com/community/tutorials/how-to-import-modules-in-python-3) the `chunkgpt.chunkgpt` library in order to use its objects and functions for chunking and summarizing large pieces of text

## A note on Environment Variables

I'm not sure your `OPENAI_API_KEY.env` file will actually load that environment variable into your environment. I'd recommend checking out [this documentation](https://kinsta.com/knowledgebase/what-is-an-environment-variable/) for more information on using environment variables, and/or consulting with AI assistants like ChatGPT to properly configure your environment variables for use.

ChunkGPT also offers a way to [hardcode your API key](https://github.com/dimays/chunkgpt/#explicitly-define-your-openai-api-key) directly into the script, if you're using this for your own personal use-case and have no need to store your API key securely in your script.

---

I hope this helps! Since this appears to be a usage problem and not an issue with the code, I am closing this issue.
